spring.application.name=app
spring.mongodb.uri=mongodb://localhost:27017/employeedb
spring.data.mongodb.auto-index-creation=true
server.servlet.context-path=/api/v1


# Kafka broker address
spring.kafka.bootstrap-servers=localhost:9092

# Producer config (your app sends events)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer config (if this app also consumes events)
spring.kafka.consumer.group-id=employee-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Don't crash app startup if Kafka broker is unavailable
spring.kafka.listener.missing-topics-fatal=false